services:
  # gigahouse_webapi:
  #   image: ferraronet/gigahouse_webapi:latest
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #     - ASPNETCORE_URLS=http://+:8085
  #     - ConnectionStrings__DefaultConnection=Host=easypainel.gigahouse.com.br;Port=5432;Database=gigahouse;Username=postgres;Password=33279711498B7B2F1319689558AF4
  #     - MongoDbSettings__ConnectionString=mongodb://admin:Darker1007@easypainel.gigahouse.com.br:27017
  #     - MongoDbSettings__DatabaseName=gigahouse
  #     - MongoDbSettings__CollectionName=WebScraping
  #     - RabbitMqSettings__ConnectionString=amqp://admin:Darker1007@gigahouse_queue:5672
  #     - RabbitMqSettings__QueueWebApiName=WebApi
  #     - RabbitMqSettings__QueueWorkerApiName=WorkerApi
  #     - RabbitMqSettings__QueueWebScrapingName=WebScraping
  #     - Jwt__SecretKey=a14a4ea06097293250cf89b033495bae94f7493703483f10fe661e5f459c5a697aedb85582bed201ad95b6c7eba70f57d59bc68737e348002e076487840cff042721a0020e3ab9db34426c617eb59f49691c9d5c041d4ab120b7d6efbdfe5e8a37fb13ea0aa6e6c6aed881a7e41a913d10a08ac639c371240586b38c9fbb6d213752e7216abeab82c0482e1f17af98e7e78d17d86a68ecda2e537a39aab4c0cb534b7e74e6acfb93e383029e32fba3ff339abdd74e4aa9203255bc92e2a2cedc5f1ca82c7292a8ea89150ee732250a68b982f70185614822bec3c02f9e073194790396618fc50b25479f38f5bb799b6cbaf340e1756d3b1991c5d449a0a095c7
  #   ports:
  #     - "8085:8085"
  #   depends_on:
  #   #   gigahouse_database:
  #   #     condition: service_healthy
  #     gigahouse_queue:
  #       condition: service_healthy
  #   #   gigahouse_nosql:
  #   #     condition: service_healthy
  #   tty: true

  # gigahouse_worker_webapi:
  #   image: ferraronet/gigahouse_workerapi:latest 
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #     - ConnectionStrings__DefaultConnection=Host=easypainel.gigahouse.com.br;Port=5432;Database=gigahouse;Username=postgres;Password=33279711498B7B2F1319689558AF4
  #     - MongoDbSettings__ConnectionString=mongodb://admin:Darker1007@easypainel.gigahouse.com.br:27017
  #     - MongoDbSettings__DatabaseName=gigahouse
  #     - MongoDbSettings__CollectionName=WebScraping
  #     - RabbitMqSettings__ConnectionString=amqp://admin:Darker1007@gigahouse_queue:5672
  #     - RabbitMqSettings__QueueWebApiName=WebApi
  #     - RabbitMqSettings__QueueWorkerApiName=WorkerApi
  #     - RabbitMqSettings__QueueWebScrapingName=WebScraping
  #     - Jwt__SecretKey=a14a4ea06097293250cf89b033495bae94f7493703483f10fe661e5f459c5a697aedb85582bed201ad95b6c7eba70f57d59bc68737e348002e076487840cff042721a0020e3ab9db34426c617eb59f49691c9d5c041d4ab120b7d6efbdfe5e8a37fb13ea0aa6e6c6aed881a7e41a913d10a08ac639c371240586b38c9fbb6d213752e7216abeab82c0482e1f17af98e7e78d17d86a68ecda2e537a39aab4c0cb534b7e74e6acfb93e383029e32fba3ff339abdd74e4aa9203255bc92e2a2cedc5f1ca82c7292a8ea89150ee732250a68b982f70185614822bec3c02f9e073194790396618fc50b25479f38f5bb799b6cbaf340e1756d3b1991c5d449a0a095c7
  #   depends_on:
  #     gigahouse_webapi:
  #       condition: service_started
  #   tty: true

  # gigahouse_worker_webscraping:
  #   image: ferraronet/gigahouse_workerscraping:latest
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #     - ConnectionStrings__DefaultConnection=Host=easypainel.gigahouse.com.br;Port=5432;Database=gigahouse;Username=postgres;Password=33279711498B7B2F1319689558AF4
  #     - MongoDbSettings__ConnectionString=mongodb://admin:Darker1007@easypainel.gigahouse.com.br:27017
  #     - MongoDbSettings__DatabaseName=gigahouse
  #     - MongoDbSettings__CollectionName=WebScraping
  #     - RabbitMqSettings__ConnectionString=amqp://admin:Darker1007@gigahouse_queue:5672
  #     - RabbitMqSettings__QueueWebApiName=WebApi
  #     - RabbitMqSettings__QueueWorkerApiName=WorkerApi
  #     - RabbitMqSettings__QueueWebScrapingName=WebScraping
  #     - Jwt__SecretKey=a14a4ea06097293250cf89b033495bae94f7493703483f10fe661e5f459c5a697aedb85582bed201ad95b6c7eba70f57d59bc68737e348002e076487840cff042721a0020e3ab9db34426c617eb59f49691c9d5c041d4ab120b7d6efbdfe5e8a37fb13ea0aa6e6c6aed881a7e41a913d10a08ac639c371240586b38c9fbb6d213752e7216abeab82c0482e1f17af98e7e78d17d86a68ecda2e537a39aab4c0cb534b7e74e6acfb93e383029e32fba3ff339abdd74e4aa9203255bc92e2a2cedc5f1ca82c7292a8ea89150ee732250a68b982f70185614822bec3c02f9e073194790396618fc50b25479f38f5bb799b6cbaf340e1756d3b1991c5d449a0a095c7
  #   depends_on:
  #     gigahouse_webapi:
  #       condition: service_started
  #   tty: true

  # gigahouse_worker_scheduler:
  #   image: ferraronet/gigahouse_workerscheduler:latest
  #   build:
  #     context: .
  #     dockerfile: GigaHouse.Worker.Scheduler/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #     - ConnectionStrings__DefaultConnection=Host=easypainel.gigahouse.com.br;Port=5432;Database=gigahouse;Username=postgres;Password=33279711498B7B2F1319689558AF4
  #     - MongoDbSettings__ConnectionString=mongodb://admin:Darker1007@easypainel.gigahouse.com.br:27017
  #     - MongoDbSettings__DatabaseName=gigahouse
  #     - MongoDbSettings__CollectionName=WebScraping
  #     - RabbitMqSettings__ConnectionString=amqp://admin:Darker1007@gigahouse_queue:5672
  #     - RabbitMqSettings__QueueWebApiName=WebApi
  #     - RabbitMqSettings__QueueWorkerApiName=WorkerApi
  #     - RabbitMqSettings__QueueWebScrapingName=WebScraping
  #     - Jwt__SecretKey=a14a4ea06097293250cf89b033495bae94f7493703483f10fe661e5f459c5a697aedb85582bed201ad95b6c7eba70f57d59bc68737e348002e076487840cff042721a0020e3ab9db34426c617eb59f49691c9d5c041d4ab120b7d6efbdfe5e8a37fb13ea0aa6e6c6aed881a7e41a913d10a08ac639c371240586b38c9fbb6d213752e7216abeab82c0482e1f17af98e7e78d17d86a68ecda2e537a39aab4c0cb534b7e74e6acfb93e383029e32fba3ff339abdd74e4aa9203255bc92e2a2cedc5f1ca82c7292a8ea89150ee732250a68b982f70185614822bec3c02f9e073194790396618fc50b25479f38f5bb799b6cbaf340e1756d3b1991c5d449a0a095c7
  #   depends_on:
  #     gigahouse_webapi:
  #       condition: service_started
  #   tty: true

  # gigahouse_database:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: gigahouse
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: saasgigahouse
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U admin -d gigahouse"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # gigahouse_nosql:
  #   image: mongo:8.0
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: saasgigahouse
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   healthcheck:
  #     test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  gigahouse_queue:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: saasgigahouse
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data: