version: '3.8'

services:
  app:
    image: gigahouseapp:latest 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_CONNECTIONSTRING: Server=mysql;Port=3306;Database=gigahouse;Uid=root;Pwd=@Gigahouse123;
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: gigahouse
      MYSQL_USER: gigahouse
      MYSQL_PASSWORD: "@Gigahouse123"
      MYSQL_ROOT_PASSWORD: "@Gigahouse123"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
